name: Create Cluster

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: MicroShift OpenShift Cluster
        uses: container-tools/microshift-action@v0.3.0
